# Generated by Django 2.2.6 on 2019-12-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentEntry',
        ),
    ]
